# Generated by Django 5.0 on 2024-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_contact', models.CharField(max_length=20)),
                ('client_mail', models.EmailField(max_length=250)),
                ('client_DOB', models.DateField()),
                ('client_address', models.CharField(max_length=500)),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(blank=True, max_length=50, null=True)),
                ('client_pin', models.IntegerField(max_length=12)),
                ('occupation', models.CharField(choices=[('self_employed', 'Self Employed'), ('govt_employee', 'Government Employee'), ('private_employee', 'Private Employee'), ('others', 'Others')], max_length=20)),
            ],
        ),
    ]
