# Generated by Django 5.0 on 2024-03-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_pin',
            field=models.IntegerField(),
        ),
    ]
