# Generated by Django 5.0 on 2024-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
