# Generated by Django 5.0 on 2024-03-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_agent_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=50)),
                ('property_types', models.CharField(choices=[('residential ', 'Residential'), ('commercial ', 'Commercial'), ('others', 'Others')], max_length=20)),
                ('size', models.CharField(max_length=100)),
                ('property_age', models.IntegerField()),
                ('property_cost', models.CharField(max_length=5000)),
                ('loan_availability', models.BooleanField(default=False)),
                ('property_description', models.TextField(max_length=500)),
                ('property_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agent')),
            ],
        ),
    ]
