# Generated by Django 5.0 on 2024-03-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
