# Generated by Django 5.0 on 2024-03-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_property_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=50)),
                ('project_area', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=1000)),
                ('add_projects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
    ]
