# Generated by Django 5.0 on 2024-03-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agent'),
        ),
    ]
