# Generated by Django 5.0 on 2024-03-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_property_property_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='add_projects',
            new_name='add_properties',
        ),
    ]
