# Generated by Django 5.0 on 2024-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_project_add_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='add_properties',
        ),
        migrations.AddField(
            model_name='project',
            name='add_properties',
            field=models.ManyToManyField(blank=True, null=True, related_name='project', to='main.property'),
        ),
    ]
