# Generated by Django 5.0 on 2024-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='main.amenity'),
        ),
    ]
