# Generated by Django 5.0 on 2024-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.IntegerField(default=1)),
            ],
        ),
    ]
