# Generated by Django 5.0 on 2024-03-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_propertytypes'),
    ]

    operations = [

    ]
