# Generated by Django 5.0 on 2024-03-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.source')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('property_Types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propertytypes')),
            ],
        ),
    ]
