# Generated by Django 5.0 on 2024-03-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
