# Generated by Django 5.0 on 2024-03-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_leads_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.propertytypes'),
        ),
    ]
