# Generated by Django 5.0 on 2024-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_property_property_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
