# Generated by Django 5.0 on 2024-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
