# Generated by Django 5.0 on 2024-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_leads_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='area_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='area_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
