# Generated by Django 5.0 on 2024-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_area_max_leads_max_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(choices=[('attempted', 'Attempted'), ('unattempted', 'Unattempted')], default='unattempted', max_length=50),
        ),
    ]
