# Generated by Django 5.0 on 2024-03-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='remarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments'),
        ),
    ]
