# Generated by Django 5.0 on 2024-03-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_leads_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='remarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='main.comments'),
        ),
    ]
