# Generated by Django 5.0 on 2024-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_leads_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
