# Generated by Django 5.0 on 2024-04-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propertytypes'),
        ),
    ]
